### ISSUE TITLE
Bot doesn't recognise garbage lines

### ISSUE THREAD

**Issue by NameLmao** [mikhail-vlasenko/Tetris-AI#5]
Bot cannot detect garbage lines, may be the colour of the garbage

**Comment by mikhail-vlasenko** [comment]
besides the garbage, does the bot play well?

I clearly remember implementing garbage detection for the game the bot was originally made for, so it should be an easy fix.

**Comment by NameLmao** [comment]
Very satisfied with the bot's ability to survive Tetris positions, does the bot recognise garbage using RGB values of the garbage?  If so, that could be the issue since different Tetris games use different colours.

**Comment by mikhail-vlasenko** [comment]
glad to hear!
yes, it uses RGB values indeed, the garbage was white in our game. the corresponding lines are 
```python
field_white0 = np.array(field[:, :, 0] > 200, int)
field_white1 = np.array(field[:, :, 1] > 200, int)
field_white2 = np.array(field[:, :, 2] > 200, int)
```
in `data.py`

**Comment by NameLmao** [comment]
That's probably the issue, the garbage on tetr.io is darker than white, I'll do some tinkering and see what the proper RGB values should be.

**Comment by NameLmao** [comment]
Entered the RGB values which are 28, 28, 28, bot stopped playing altogether, could this be something with the < and > symbols?

**Comment by mikhail-vlasenko** [comment]
I assume the garbage is black in your case? then of course you need to change '>' to '<'. otherwise everything is recognized as garbage

**Comment by NameLmao** [comment]
It's got an rgb value of 28 for all colours, using > and < both cause the bot to stop playing entirely, could be because the colour range is a bit weird

**Comment by mikhail-vlasenko** [comment]
are you sure there is nothing else on the screen that has rgb < 28? 
you need to come up with an rbg range that includes only garbage, not the actual pieces, not the background

**Comment by mikhail-vlasenko** [comment]
don't forget that you can look at the field array to know exactly what the bot sees

**Comment by NameLmao** [comment]
When it looks for under 28 the array sees a line at the very top and nothing else, when looking for above 28 the array just sees nothing

**Comment by mikhail-vlasenko** [comment]
consider using `20 < field[:, :, 0] < 30` or something along those lines

**Comment by NameLmao** [comment]
tried doing that, the array always shows this
[[0 0 0 0 1 1 0 0 0 0]
 [0 0 0 0 1 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 1 1 0]
 [0 0 0 0 0 0 0 1 1 0]
 [1 0 0 0 0 0 0 1 1 0]
 [1 0 0 0 0 0 0 1 1 0]
 [1 1 0 0 0 0 0 1 1 0]
 [1 1 0 0 0 0 0 1 1 0]
 [1 1 1 0 0 0 1 1 1 0]
 [1 1 1 0 1 0 1 1 1 0]
 [1 1 1 0 1 0 1 1 1 0]
 [1 1 1 1 1 0 1 1 1 0]
 [1 0 1 1 1 1 1 1 1 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]

**Comment by mikhail-vlasenko** [comment]
well, I don't know what it should look like in this case, but the idea is to have garbage encoded just like a regular block. So 1 for pieces/garbage and 0 for empty space

**Comment by NameLmao** [comment]
The zeros at the bottom are supposed to be mostly 1s represented by garbage but the bot doesn’t recognise them, all rgb values entered either make the bot stop playing or not detect correctly

**Comment by mikhail-vlasenko** [comment]
ok it might be that I was wrong and the 'white' stuff is for garbage, it might also be for a huge TETRIS text appearing in some cases. In any case, the `get_field_from_screen` function is honestly not very intuitive, so it would probably be useful for you to rewrite most of it. 

As the field parameter, you get an rbg image, an array of shape (h, w, 3). You need to return another array of shape (h, w) where an element is 1 if the image has a piece or garbage on this pixel

**Comment by NameLmao** [comment]
would the shape array come from the figures.py file?

**Comment by mikhail-vlasenko** [comment]
did you manage to do it?

the exact values of h and w shouldn't really matter, and can vary per user, just return the same as it was

**Comment by NameLmao** [comment]
Still unable to figure out why the bot can’t detect the garbage, from what I can see it doesn’t need to see the piece shape because entering a position allows the bot to just play from what it started with so the only way I can see it doesn’t detect garbage is because of the rgb values but I’m unable to set an rgb range for the garbage detection

**Comment by mikhail-vlasenko** [comment]
dont try with `field_white`, do it your own way. maybe if the background is darker than everything else, you can put 
`pieces0 = np.array(field[:, :, 0]  > bg_color,  int)` for each color and then take multiply the resulting arrays to perform 'and' operation (`field = pieces0 * pieces1 * pieces2`)

**Comment by NameLmao** [comment]
I’ll try every method I have to change it and I’ll give an update once I finish it

**Comment by NameLmao** [comment]
def get_field_from_screen(self, img):
        field = img[self.top:self.bottom, self.left:self.right]
        field0 = np.array(field[:, :, 0] <130, int)  # blue
        field1 = np.array(field[:, :, 1] <100, int)  # green
        field2 = np.array(field[:, :, 2] <90, int)  # red
        field_white0 = np.array(field[:, :, 0] >200, int)
        field_white1 = np.array(field[:, :, 1] >200, int)
        field_white2 = np.array(field[:, :, 2] >200, int)
        pieces0 = np.array(field[:, :, 2] >0, int)
        pieces1 = np.array(field[:, :, 2] >0, int)
        pieces2 = np.array(field[:, :, 2] >0, int)
        pieces = pieces0 * pieces1 * pieces2
        field_white = field_white0 * field_white1 * field_white2
        field = field0 * field1 * field2 + field_white
        field = 1 - field
        return field

Tried this but it makes python unresponsive, no error code, no field image, and no game inputs

**Comment by mikhail-vlasenko** [comment]
Hello there @NameLmao ,

I got some time and refactored a large portion of the code, now it should be much more readable.

Besides that, I adapted the bot to tetr.io multiplayer (so garbage detection included), and it performs very well. The last commit on the master branch, with a few modifications to the new `config.py`, should get you there!

**Comment by NameLmao** [comment]
Ok, I’ll check the new code, thank you for your dedication

**Comment by mikhail-vlasenko** [comment]
Did you find any success with the new code?

**Comment by NameLmao** [comment]
Sorry for not responding in a long time, I forgot about this. The bot works much better now that it detects garbage though, thank you.

**Comment by mikhail-vlasenko** [comment]
consider starring the project if you liked it!
